### ISSUE TITLE
axios-client 수정

### ISSUE THREAD

**Issue by horororok** [codeitFE11-part3-team7/wikid#146]
- GET aticles/{articleId} 부분 인증 필요

**Comment by junghwaYang** [comment]
@horororok 태훈님 이거 작업 언제 끝나실까요? 이 작업이 끝나야 #128 이슈 작업 할 수 있어서요!

**Comment by horororok** [comment]
> @horororok 태훈님 이거 작업 언제 끝나실까요? 이 작업이 끝나야 #128 이슈 작업 할 수 있어서요!

@junghwa1996 pr 올렸습니다
