### ISSUE TITLE
아이폰 16 버전 이상 사파리에서 isAuthenticated 상태 체크

### ISSUE THREAD

**Issue by junghwaYang** [codeitFE11-part3-team7/wikid#259]
# 해당 버그는 본 이슈에서 작업 진행하겠습니다
- [x] `ProfileContext.tsx` 디버깅 코드 추가 

## 확인된 사항(디버깅 결과)

- [x] ios 사파리 웹뷰에서 로컬 스토리지에 정상적으로 토큰값이 담겨야함
- [x] 로컬 스토리지의 값을 정상적으로 불러오는지 확인
- [x] 위 조건이 확인되면, false와 true 상태를 잘 return 하는지 확인

## 이슈 해결 전제조건

- [x] pc 웹브라우저에서 정상동작 해야함
- [x] mo 안드로이드, ios 16이하(지이님 버전)에서도 정상동작 해야함
- [x] 다른 웹뷰 확인(카카오,네이버,크롬,웨일 등)
- [x] ios 16버전 이상에서도 정상동작해야함

**Comment by junghwaYang** [comment]
@solprime 해당 브랜치에 인증 관련 디버깅 코드 찍어서 푸시 후 노티 주세요

**Comment by solprime** [comment]
> @solprime 해당 브랜치에 인증 관련 디버깅 코드 찍어서 푸시 후 노티 주세요

추가했습니다 확인해주세요

**Comment by junghwaYang** [comment]
> > @solprime 해당 브랜치에 인증 관련 디버깅 코드 찍어서 푸시 후 노티 주세요
> 
> 추가했습니다 확인해주세요

확인했습니다! 디버깅 후 결과 노티 드리겠습니다!
