### ISSUE TITLE
프로필인풋 컴포넌트

### ISSUE THREAD

**Issue by crazyupinc-design** [codeitFE11-part3-team7/wikid#34]
- [ ] 프로필인풋 컴포넌트
- [ ] 텍스트, 날짜 형태의 프로필 정보를 받을 수 있도록 설정.
- [ ] 디자인 설정

**Comment by junghwaYang** [comment]
@crazyupinc-design  해당 34번 브랜치 사용안하시는게 맞을까요? closed만 하면 브랜치 삭제가 안되어서요 !
